/*

By CodeSoft

Create a program that generates a random number and asks the
user to guess it. Provide feedback on whether the guess is too
high or too low until the user guesses the correct number.

*/

#include <iostream>
#include <cstdlib>
#include <ctime>

int main()
{

    std::srand(static_cast<unsigned int>(std::time(0)));

    int randomNumber = std::rand() % 100 + 1;

    std::cout << "\n\n\n";

    std::cout << "Number generated by Compueter is : " << randomNumber << "\n";

    int guess;
    int attempts = 0;

    std::cout << "\n"
              << "Guess the number between 1 and 100 !!!" << std::endl;

    do
    {
        std::cout << "\n"
                  << "Enter your guess : ";
        std::cin >> guess;
        attempts++;

        if (guess < randomNumber)
        {
            std::cout << "\n"
                      << "Too low! Try again." << std::endl;

            std::cout << "\n"
                      << "| You failed " << attempts << " times.| "
                      << " ....... "
                      << "| Concentrate on the Game !!! |"
                      << "\n\n";
        }
        else if (guess > randomNumber)
        {
            std::cout << "\n"
                      << "Too high! Try again." << std::endl;

            std::cout << "\n"
                      << "| You failed " << attempts << " times.| "
                      << " ....... "
                      << "| Concentrate on the Game !!! |"
                      << "\n\n";
        }
        else
        {
            std::cout << "\n"
                      << "Congratulations! You guessed the number " << randomNumber << " correctly in " << attempts << " attempts!" << std::endl;

            std::cout << "\n"
                      << "Hurray !!! Mission Passed ........... Respect ++++";
        }

    } while (guess != randomNumber);

    return 0;
}
